### ISSUE TITLE
It send the metadata/context in a wrong format

### ISSUE THREAD

**Issue by gyurobenjamin** [bugsnag/bugsnag-psr-logger#25]
Currently bugsnag can't handle multidimensional array/object as metadata/custom data.

So this one is fine:
```php
Log::error('whatever', ['error' => 'single']);
```

But this one will miss the error2:
```php
Log::error('whatever', ['error' => 'single', 'error2' => ['error2.1' => 'multi']]);
```

**Comment by Cawllec** [comment]
Hi @gyurobenjamin, I've looked at your examples here but both seem to work in the expected way.

The single example adds the `error` metadata to the `custom` tab:
![Single example](https://user-images.githubusercontent.com/7754028/32541066-751eabde-c466-11e7-90fe-1d848454c8d9.png)

The multi example again adds the `error` metadata to the `custom` tab:
![Multi example - error](https://user-images.githubusercontent.com/7754028/32541067-75336e02-c466-11e7-9c39-1508a9573309.png)

It also creates a new tab `error2` to represent the sub-array.
![Multi example - error2](https://user-images.githubusercontent.com/7754028/32541068-7548f8da-c466-11e7-922d-3cdc652a4e58.png)

Can you let me know if you see something different to this from your examples in the dashboard?

**Comment by Cawllec** [comment]
Code used to test:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$client = Bugsnag\Client::make('API KEY');

$logger = new Bugsnag\PsrLogger\BugsnagLogger($client);

$logger->error('whatever', ['error' => 'single']);
#$logger->error('whatever2', ['error' => 'single', 'error2' => ['error2.1' => 'multi']]);
```

**Comment by gyurobenjamin** [comment]
I use it with Laravel 5.1 and "bugsnag/bugsnag-laravel": "^2.0".

My test was:
```php
\Log::error('whatever', ['error' => 'single', 'error2' => ['error2.1' => 'multi']]);
\Log::warning('whatever', ['error' => 'single', 'error2' => ['error2.1' => 'multi']]);
\Log::info('whatever', ['error' => 'single', 'error2' => ['error2.1' => 'multi']]);
```

I tried again, I haven't got any custom tab, so I completely lost the error2 in bugsnag.

Will do couple of more testing without laravel. What version did you use?

**Comment by Cawllec** [comment]
I used PHP 7.0.22, I'll run your examples with Laravel as well to verify.  Can you confirm that with your PR you are definitely seeing `error2` appearing now?

**Comment by gyurobenjamin** [comment]
@Cawllec I definitely see the error2 but not in a custom tab.
Now I tried with the last version (without my changes), and I see the new tab.

Trying to debugging what could be an issue in other cases. We parse exception and lot of huge objects here. Will do couple of testing with those now, but definitely we can't see them currently on production, not on new tab and nowhere.

**Comment by gyurobenjamin** [comment]
Ok, I found the real issue, my mistake.
If I parse any object like Exception, then this json_encode will drop it in the \Bugsnag\Report:

```php
return $this->cleanupObj(json_decode(json_encode($obj), true), $isMetaData);
```

src: https://github.com/bugsnag/bugsnag-php/blob/master/src/Report.php#L661

**Comment by Cawllec** [comment]
Ok, brilliant, so you're getting the full set of metadata you want to send coming through now?

**Comment by gyurobenjamin** [comment]
Well, still not, but it is not an issue with this project. That is an issue with the bugsnag-php. So I will close my PR and try to find a solution for the json_encode issue.

**Comment by Cawllec** [comment]
Oh, sorry, I misunderstood.  If we can keep this thread open for now to show resolution, I'll create a new one under Bugsnag-php and we can continue this there
